In [451]:
import numpy as np

In [452]:
a = [1,2,3,4]
type(a)

list

In [453]:
arr = np.array([1,2,3,4,5])

In [454]:
arr

array([1, 2, 3, 4, 5])

In [455]:
sum_arr = sum(arr)

In [456]:
sum_arr

15

In [457]:
mean_arr = arr.mean()

In [458]:
mean_arr

3.0

In [459]:
square_Arr = np.square(arr)

In [460]:
square_Arr

array([ 1,  4,  9, 16, 25])

In [461]:
mata = np.array([[1,2],[2,3]])

In [462]:
mata

array([[1, 2],
       [2, 3]])

In [463]:
matb = np.array([[4,5,4],[5,6,2]])

In [464]:
matb

array([[4, 5, 4],
       [5, 6, 2]])

In [465]:
dot = np.dot(mata, matb)

In [466]:
dot

array([[14, 17,  8],
       [23, 28, 14]])

In [467]:
type(arr)

numpy.ndarray

In [468]:
mat = np.array([
               [1,2,4,3],
                [4,53,2,6]
])

In [469]:
mat.shape

(2, 4)

In [470]:
trans_mat = mat.T

In [471]:
trans_mat

array([[ 1,  4],
       [ 2, 53],
       [ 4,  2],
       [ 3,  6]])

In [472]:
trans_mat.shape

(4, 2)

In [473]:
arr[1:3]

array([2, 3])

In [474]:
random_arr = np.random.rand(3,3)

In [475]:
random_arr

array([[0.98734878, 0.73947034, 0.23595541],
       [0.19026036, 0.89854381, 0.62257323],
       [0.84191217, 0.53692833, 0.49828669]])

In [48]:
arr_range = np.arange(0,40,3)

In [49]:
arr_range

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [50]:
zero_arr = np.zeros((2,4))

In [51]:
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
ones_arr = np.ones((3,6))

In [54]:
ones_arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [55]:
reshape_arr = ones_arr.reshape((2,9))

In [56]:
reshape_arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [64]:
mat = np.array([
               [1,2,3],
                [4,5,6]
])
print(np.sum(mat**2))

91


In [67]:
twice = np.sum(mat)*2

In [68]:
twice

42

In [72]:
np.sum(mat[mat % 2 > 0])

9

In [73]:
arr = np.array([1,2,3])
arr2 = np.array([0.1,0.2,0.3])

In [75]:
np.sum(arr+89)

273